### ISSUE TITLE
Cannot build fresh images

### ISSUE THREAD

**Issue by davidindra** [cattlepi/cattlepi#153]
Hello,
@mirceal please, I want to have a question about building custom images with this tutorial: https://github.com/cattlepi/cattlepi/blob/master/doc/BUILDING.md

I do everything as in the tutorial (only with one slight change in _tools/cfg/requirements.txt_ - removed _awscli, MarkupSafe, urllib3_ and changed to _cffi>=1.11.5_ - without this change, _make_ would fail with python conflicting dependencies). However, when images are built and served to my custom API server, build fails like you can see on following images:

![IMG_20210701_224957](https://user-images.githubusercontent.com/4839429/124189836-9f3c3b00-dac1-11eb-84f3-230016cb0f01.jpg)
![IMG_20210701_225001](https://user-images.githubusercontent.com/4839429/124189841-a2372b80-dac1-11eb-9672-da3e49cfdb88.jpg)
![IMG_20210701_225006](https://user-images.githubusercontent.com/4839429/124189852-a5321c00-dac1-11eb-9e14-550c87f4b2df.jpg)
![IMG_20210701_225023](https://user-images.githubusercontent.com/4839429/124189860-a7947600-dac1-11eb-888d-024c7908e3ec.jpg)
![IMG_20210701_225031](https://user-images.githubusercontent.com/4839429/124189865-a95e3980-dac1-11eb-83fb-58708214e64e.jpg)
![IMG_20210701_225058](https://user-images.githubusercontent.com/4839429/124189872-ab27fd00-dac1-11eb-931e-6c4fc645cdce.jpg)

Please, can you give me some advice for what am I doing wrong? I can send those images to you if you are interester, or investigate it based on your tips, whatever you want.

Thanks very much for your help,
David

**Comment by mirceal** [comment]
Hey @davidindra 

Thank for the detailed issue.
2 things:
1) can you open a PR with the changes you did to the requirments (and any other changes for me to try to replicate?) 
2) I haven't tried building this in a while so its possible that something it depends changed. 

for 1) will wait for your input
i'll try 2) when i have a few spare cycles to see if i can repro. thanks.

**Comment by davidindra** [comment]
Thank you very much for your quick reply. Will make PR around 9AM CEST.

**Comment by mirceal** [comment]
tested this locally. the deps were broken.
fix is in: https://github.com/cattlepi/cattlepi/pull/154

please pull latest and give this one more shot. 

thank you for the feedback.

**Comment by mirceal** [comment]
@davidindra any feedback?
