### ISSUE TITLE
configure wifi on boot from config

### ISSUE THREAD

**Issue by mirceal** [cattlepi/cattlepi#17]
right now the boot and the device work on the wired network interface (eth0) only. 
this would add support to configure the wifi / enable network connectivity via wifi. 
on 1st boot the device would need to be on the wired network, get the wifi params and after that it could work without a wired connection.

**Comment by zmrow** [comment]
Super interested in this.  Will get on it after #5

**Comment by zmrow** [comment]
In progress

**Comment by zmrow** [comment]
Message sent to dev mailing list for design questions.

**Comment by mirceal** [comment]
answered. for everyone else, discussion is here: https://groups.google.com/forum/#!topic/cattlepi-dev/VK5gCOY51ow

**Comment by zmrow** [comment]
There's a decent amount of gotchas here.  The basic process isn't too difficult (and I have some working skeleton code), just need to work through the few scenarios as there's a few dragons lurking.  :)

**Comment by mirceal** [comment]
dragon driven development you say? :rofl:
