### ISSUE TITLE
requirements.txt contains "pkg-resources==0.0.0", which causes pip to choke

### ISSUE THREAD

**Issue by zmrow** [cattlepi/cattlepi#29]
The ```tools/cfg/requirements.txt``` file contains a line ```pkg-resources==0.0.0```, which causes the pip installs to choke when running ```make envsetup```.

<pre>
...
Collecting MarkupSafe==1.0 (from -r requirements.txt (line 12))
Collecting paramiko==2.4.1 (from -r requirements.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/3e/db/cb7b6656e0e7387637ce850689084dc0b94b44df31cc52e5fc5c2c4fd2c1/paramiko-2.4.1-py2.py3-none-any.whl
<b>Collecting pkg-resources==0.0.0 (from -r requirements.txt (line 14))
  Could not find a version that satisfies the requirement pkg-resources==0.0.0 (from -r requirements.txt (line 14)) (from versions: )
No matching distribution found for pkg-resources==0.0.0 (from -r requirements.txt (line 14))</b>
</pre>

As per https://stackoverflow.com/a/40167445, running ```pip freeze > requirements.txt``` in Ubuntu/Debian (not sure if this is what you do) causes this to happen.  Something something bad metadata?

Anyway, the suggestion is to add a `make` target removing that line from the output of ```pip freeze```:

```
freeze:
    pip freeze | grep -v "pkg-resources" > requirements.txt
```

Sounds perfectly reasonable to me, but I'm not sure what your workflow was when putting this together.  If you're good with that idea, I'll add the Makefile target and update the ```requirements.txt```

**Comment by mirceal** [comment]
The workflow was... manually running pip freeze :) 
I am running a Debian/Ubuntu-ish OS, so I think it's the issue you're reference on SO. 

Making the change in the makefile makes sense, but you're maybe going to run into a bit of trouble (you're not under the virtual env so pip may not work with the correct dependencies). 

What about doing this change in setup_env.sh and just remove the line from the file without relying on pip?

**Comment by zmrow** [comment]
Yep - this is the right approach.  Keep it simple.  👍
