### ISSUE TITLE
build the rootfs image on an emulator

### ISSUE THREAD

**Issue by mirceal** [cattlepi/cattlepi#4]
the idea here is to not use a physical RPI to build the images. 
more research needs to go into how to do this, but this should be doable.

Advantages of this approach:
 * could setup a builder in the cloud that periodically updates the image 
 * could potentially setup building images (based on some sort of spec) for others 
 * don't have to touch the SD card even for the builder

**Comment by captn3m0** [comment]
I looked a little into this as well. The most interesting lead was QEMU + binfmt and just run the builder inside Docker: https://gist.github.com/Manu343726/ca0ceb224ea789415387

**Comment by mirceal** [comment]
thanks @captn3m0 This looks promising, but the Raspian image is from 2015 :( https://hub.docker.com/r/philipz/rpi-raspbian/~/dockerfile/ Guess we need a little more digging on how to produce an updated docker image or how to bypass docker completely

**Comment by mirceal** [comment]
after looking the support that is available in Qemu and other ways that people hack together a virtual Pi, I don't believe that running this in an emulator is the way to go. (you need a special built kernel and you cannot run the stock raspbian - both of which make this a no-starter). 

I believe there is a way to setup the CI/continuously building the images by using a combination of https://github.com/cattlepi/cattlepi/issues/21, https://github.com/cattlepi/cattlepi/issues/18 and https://github.com/cattlepi/cattlepi/issues/16

All other work that's going to be done for the CI part will happen under https://github.com/cattlepi/cattlepi/issues/15 once we have the plumbing in place.
