### ISSUE TITLE
Kernel panic on command `sudo shutdown -h now`

### ISSUE THREAD

**Issue by zmrow** [cattlepi/cattlepi#42]
Starting point is a successfully provisioned and booted cattlepi (master branch) instance with no customizations.

Ssh in the the pi, issue the command `sudo shutdown -h now` and if the pi is connected to a monitor you'll see a nasty kernel panic stack trace with the message `Rebooting in 20 seconds` at the bottom.

Then the pi will reboot normally.

Have you seen this behavior?

**Comment by mirceal** [comment]
I have seen this a few of times, but not on shutdown. Usually on boot. 
IIRC this happens on the same Pi (I have a 6 of them) which made me think it's maybe the SD card or the hardware. It did not happen enough times for me to spend a lot of time trying to figure out what's going on. 

**Does it consistently reproduce for you or was this a one time appearance?**
The rebooting in 20 seconds is configurable via a kernel boot param (the panic=20 in [here](https://github.com/cattlepi/cattlepi/blob/2b33a8cc1f77a90a32081e16698c0df8af124e53/templates/raspbian/tasks/initramfs.yml.mustache#L50))

**Comment by zmrow** [comment]
It consistently reproduces for me.

I'll give it a shot on another Pi and SD card and follow up here.

**Comment by zmrow** [comment]
Super busy weekend. Will give it a shot this week!

**Comment by zmrow** [comment]
I'm unable to reproduce this on different raspberry pi hardware and SD card...  This doesn't bode well for that piece of hardware... 👎 

Closing this for now!
