### ISSUE TITLE
Curl doesn't seem to honor timeout flags

### ISSUE THREAD

**Issue by zmrow** [cattlepi/cattlepi#60]
https://github.com/cattlepi/cattlepi/blob/9d8493f921c2c08b230c6a4170329c5062cec481/templates/raspbian_cattlepi/resources/usr/share/initramfs-tools/scripts/cattlepi-base/helpers#L133

I consulted the man pages and it seems that using the flags `--connect-timeout` and `-m` should limit the time that `curl` takes to try and do its work.  However I've observed that curl takes up to 5 minutes to timeout.  This means that when there is no network, the initramfs code hangs for a bit whenver we call curl from this function (currently twice for `raspbian_cattlepi`)

So while the code does what it's supposed to concerning offline mode, it does take longer than I would like.

Related to #44 .

**Comment by zmrow** [comment]
I may have this fixed, will follow up this weekend.

**Comment by mirceal** [comment]
@zmrow Do you remember what the fix was here?

**Comment by mirceal** [comment]
closing this for now as low pri. feel free to reopen / contribute the fix
