### ISSUE TITLE
Panic does not reboot immediately

### ISSUE THREAD

**Issue by zmrow** [cattlepi/cattlepi#61]
https://github.com/cattlepi/cattlepi/blob/9d8493f921c2c08b230c6a4170329c5062cec481/templates/raspbian_cattlepi/resources/usr/share/initramfs-tools/scripts/cattlepi-base/helpers#L268

It seems that `panic` should reboot immediately.  Currently it does not and moves on to the next step in the code.  This is easily reproduced by pulling the network cable and booting the initramfs.

Consulting the [man pages here](http://manpages.ubuntu.com/manpages/bionic/man8/initramfs-tools.8.html), perhaps we should be setting `panic=20` and `break` in the cmdline?  Relevent text from man pages:  

```
Beware that  if  both "panic" and "break" are present, initramfs will not 
spawn any shells but reboot instead.
```

**Comment by mirceal** [comment]
don't know if it matters or i'm doing something differently but I've never had an issue getting an rescue shell even with panic specified. maybe I did not pay attention and/or this was in the initial stages of development, but I will check this again. 

also the panic=X was meant as a way to give you a chance to see what happened before the reboot, but in the totally automatic [headless] setup yes, i makes little sense to have 20 sec delay.

**Comment by zmrow** [comment]
[It was late when I opened this...] AFter thinking about this a bit more, I think you're right.  It's useful to see what happened.  In a totally headless setup I suppose it doesn't make much sense but I don't think saving 20 seconds is doing us a huge favor.

I'm going to close this - feel free to re-open if you think it has merit.
