### ISSUE TITLE
write how-to for "booting without the network"

### ISSUE THREAD

**Issue by mirceal** [cattlepi/cattlepi#76]
For here: https://cattlepi.com/howto/

Implemented in
Issue: #19 
PR: #44

**Comment by mirceal** [comment]
Hey @zmrow 
Would you be interested in doing a short write-up on what the "networkless" boot is and how it works (to be put here: https://cattlepi.com/howto/) ?
Thanks

**Comment by zmrow** [comment]
PR for docs opened [here](https://github.com/cattlepi/cattlepi-website/pull/8) . Please review and I can merge.

**Comment by mirceal** [comment]
reviewed and merged. will rebuild the website shortly
